[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 8MB

; USB OTG nativo com TinyUSB (composite HID+CDC)
build_unflags = -DARDUINO_USB_MODE=1
build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=3
    -DCFG_TUD_CDC_RX_BUFSIZE=512
    -DCFG_TUD_CDC_TX_BUFSIZE=512

lib_deps =
    https://github.com/mathieucarbou/AsyncTCP.git
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    ArduinoJson@^7

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

upload_speed = 921600
